package com.cognologix.bankingApplication.globleObjectLists;


import com.cognologix.bankingApplication.dto.AccountDto;
import com.cognologix.bankingApplication.entities.Account;
import com.cognologix.bankingApplication.entities.Customer;
import com.cognologix.bankingApplication.exceptions.AccountAlreadyExistException;
import com.cognologix.bankingApplication.exceptions.AccountNotAvailableException;
import com.cognologix.bankingApplication.exceptions.InsufficientBalanceException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;

//DAO for banking operations
@Component
public class DataSoucrce {
    //list stores all the information of accounts
    List<Account> accounts = new ArrayList<>();

    @Autowired
    DataSouceForCustomer dataSouceForCustomer;

    //save account for customer, create account and return accountDetails
    public Account saveObject(AccountDto accountDto) {

        //new account for holding information
        Account account = new Account();

        //getting customer from existing customers and storing information into account entity
        Customer customer = dataSouceForCustomer.getCustomerById(accountDto.getCustomerId());

        //autogenerated account number set to account entity
        account.setAccountNumber(generateAccountNumber());

        //set information from DTO gives from UI into the account
        account.setAccountID(accountDto.getAccountID());
        account.setAccountType(accountDto.getAccountType());
        account.setBalance(accountDto.getBalance());

        //creating new customer and storing into account entity
        //account holding the data of customer into this object
        Customer customerInAccount = new Customer();

        customerInAccount.setAdharNumber(customer.getAdharNumber());
        customerInAccount.setCustomerId(customer.getCustomerId());
        customerInAccount.setCustomerName(customer.getCustomerName());
        customerInAccount.setDateOfBirth(customer.getDateOfBirth());
        customerInAccount.setPanCardNumber(customer.getPanCardNumber());
        customerInAccount.setEmailId(customer.getEmailId());
        customerInAccount.setGender(customer.getGender());

        //adding data into customer and customer save into account
        account.setCustomer(customerInAccount);

        //this indicates single customer have different account
        List<Account> matchingAccount = accounts.stream()
                .filter(accountToCheck -> accountToCheck.getCustomer().getCustomerId() == accountDto.getCustomerId())
                .filter(accountInList -> accountInList.getAccountType().equalsIgnoreCase(accountDto.getAccountType()))
                .collect(Collectors.toList());

        //if any matching account NOT found for same customer then it saves into accounts list
        //if any matching account found for same customer then it throws exception
        if (matchingAccount.size() == 0) {
            accounts.add(account);
        } else {
            throw new AccountAlreadyExistException("This account type of the same user is already exist...");
        }

        return account;
    }

    //generate account number for new customer
    public Long generateAccountNumber() {
//        Random random = new Random();
//        String accountNumberInString = String.valueOf(Math.round(random.nextFloat() * Math.pow(10, 12)));
        Long accountNumber = Long.valueOf(1000+accounts.size());
//        Long accountNumber = Long.parseLong(accountNumberInString);
        return accountNumber;
    }

    //get all Accounts related to one customer by giving customerID
    public List<Account> getAcountsByCustomerId(Integer customerId) {
        List<Account> matchingAccounts = accounts.stream()
                .filter(account -> account.getCustomer().getCustomerId().equals(customerId))
                .collect(Collectors.toList());

        if (matchingAccounts.isEmpty())
            throw new AccountNotAvailableException("Please enter correct CustomerId, Customer for your entered id is not found OR not created...");
        else
            return matchingAccounts;
    }

    //delete customer by giving customerID
    public List<Account> deleteCustomer(Integer customerId) {
        accounts = accounts.stream()
                .filter(account -> account.getCustomer().getCustomerId() != customerId)
                .collect(Collectors.toList());
        List<Account> deletedAccounts = getAcountsByCustomerId(customerId);
        if (deletedAccounts == null) {
            throw new AccountNotAvailableException("Please enter correct account information, Account for your entered account id is not found...");
        } else {
            return deletedAccounts;
        }
    }

    //get account details by giving account number
    public Account getByAccountNumber(Long accountNumber) {
        List<Account> matchingAccount = accounts.stream()
                .filter(customer -> customer.getAccountNumber().equals(accountNumber))
                .collect(Collectors.toList());

        if (matchingAccount.isEmpty())
            throw new AccountNotAvailableException("Please enter correct account information, Account for your entered account id is not found...");
        else
            return matchingAccount.get(0);
    }

    //deposit to the account
    public void deposit(Long accountNumber, Double amount) {

        List<Account> accountForDeposite = accounts.stream()
                .filter(account -> account.getAccountNumber().equals(accountNumber)).collect(Collectors.toList());

        if (accountForDeposite.isEmpty())
            throw new AccountNotAvailableException("Please enter correct account information, Account for your entered account id is not found...");

        Account updatedAccount = accountForDeposite.get(0);
        Double currentBalance = updatedAccount.getBalance();
        Double updatedBalance = currentBalance + amount;
        accountForDeposite.get(0).setBalance(updatedBalance);

        List<Account> finalAccount = accounts.stream()
                .filter(account -> account.getAccountNumber() != accountNumber).collect(Collectors.toList());
        finalAccount.add(updatedAccount);

    }

    //withdraw from the account
    public void withdraw(Long accountNumber, Double amount) {
        List<Account> accountForWithdraw = accounts.stream()
                .filter(account -> account.getAccountNumber().equals(accountNumber)).collect(Collectors.toList());
        if (accountForWithdraw.isEmpty())
            throw new AccountNotAvailableException("Please enter correct account information, Account for your entered account id is not found...");

        Account updatedAccount = accountForWithdraw.get(0);
        Double currentBalance = updatedAccount.getBalance();
        if (currentBalance >= amount) {
            Double updatedBalance = currentBalance - amount;
            accountForWithdraw.get(0).setBalance(updatedBalance);
        } else {
            throw new InsufficientBalanceException("oop's your account has insufficient balance.....");
        }

        List<Account> finalAccount = accounts.stream()
                .filter(account -> account.getAccountNumber() != accountNumber).collect(Collectors.toList());
        finalAccount.add(updatedAccount);

    }

    //transfer amount from one account to another account
    public void transferMoney(Long accountNumberWhoSendMoney, Long accountNumberWhoRecieveMoney, Double ammountForTransfer) {
        withdraw(accountNumberWhoSendMoney, ammountForTransfer);
        deposit(accountNumberWhoRecieveMoney, ammountForTransfer);

    }

    //get current balance from given account
    public Double getCurrentBalance(Long accountNumber) {
        Account accountForCheckingBalance = getByAccountNumber(accountNumber);
        return accountForCheckingBalance.getBalance();
    }
}
